### ISSUE TITLE
Some problems with beatmap loading

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#9]
1. https://osu-js.pages.dev/play/?2116202 - This beatmap broke after replacing the storyboard parser.

![image](https://user-images.githubusercontent.com/43014304/180739235-8670a4a9-01a2-4ee8-9054-8856cef31e5b.png)

2. https://osu-js.pages.dev/play/?1006822 - I never had this problem, but i know one guy who had it. This happens every time on iOS using latest version of Safari browser.

![image](https://user-images.githubusercontent.com/43014304/180740387-afa79616-1c53-405b-9d2c-10f973ef5b86.png)

## Sub-Issues:
- [x] blueberrymuffin3/osu-storyboard-parser#1
Issue loading https://osu-js.pages.dev/play/?2116202: `Error loading beatmap: TypeError: reduce of empty array with no initial value`
- [x] blueberrymuffin3/osu-js#11
Issue loading https://osu-js.pages.dev/play/?1006822: `Error loading beatmap: RangeError: Maximum call stack size exceeded`

**Comment by blueberrymuffin3** [comment]
- [ ] Support [variables](https://osu.ppy.sh/wiki/en/Storyboard/Scripting/Variables)
Issue loading https://osu-js.pages.dev/play/?2116202: `Error loading beatmap: TypeError: reduce of empty array with no initial value`
- [ ] Large storyboards cause stack overflow on iOS Safari
Issue loading https://osu-js.pages.dev/play/?1006822: `Error loading beatmap: RangeError: Maximum call stack size exceeded`
